// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIIz26jRSxQBJPfPBeE9CEUD1KM_aWsE',
    appId: '1:1034068026280:web:bdbb2bf5125baa9a78f39d',
    messagingSenderId: '1034068026280',
    projectId: 'growintern-news',
    authDomain: 'growintern-news.firebaseapp.com',
    storageBucket: 'growintern-news.appspot.com',
    measurementId: 'G-XRNH7CJ586',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4mTnk3WN2hCNRgdSE4xjqvl9eeb_pEQ',
    appId: '1:1034068026280:android:77a500117029185878f39d',
    messagingSenderId: '1034068026280',
    projectId: 'growintern-news',
    storageBucket: 'growintern-news.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lbeQf-_qGD82ZjFIEir0J7WeCv4VQe8',
    appId: '1:1034068026280:ios:8d558ab934e057e478f39d',
    messagingSenderId: '1034068026280',
    projectId: 'growintern-news',
    storageBucket: 'growintern-news.appspot.com',
    iosBundleId: 'com.growintern.bnews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lbeQf-_qGD82ZjFIEir0J7WeCv4VQe8',
    appId: '1:1034068026280:ios:6a19ad9a3512076178f39d',
    messagingSenderId: '1034068026280',
    projectId: 'growintern-news',
    storageBucket: 'growintern-news.appspot.com',
    iosBundleId: 'com.growintern.bnews.RunnerTests',
  );
}
